version: '3.8'
services:
  everydream2trainer:
    image: ghcr.io/victorchall/everydream2trainer:main
    ports:
      - "8888:8888"
      - "6006:6006"
    environment:
      - JUPYTER_PASSWORD=test1234
    volumes:
      - .:/workspace/EveryDream2trainer
      - ./.cache:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
