version: '3.8'
services:
  everydream2trainer:
    container_name: everydream2-gpu0
    shm_size: '2gb'
    build: https://github.com/scottshireman/everydream2trainer.git
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "8888:8888"
      - "6006:6006"
    environment:
      - JUPYTER_PASSWORD=test1234
    volumes:  
      - /home/scott/everydream2-gpu0:/workspace/EveryDream2trainer
      - /home/scott/everydream2-gpu0/.cache:/root/.cache
      - /media/data/runtime:/workspace/EveryDream2trainer/runtime
      - /media/data/models:/workspace/EveryDream2trainer/models:ro
      - /media/data/captions:/workspace/EveryDream2trainer/captions:ro
    deploy:   
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
